### ISSUE TITLE
A small mistake

### ISSUE THREAD

**Issue by vba34520** [DavidMuller/davidmuller.github.io#4]
The article [How To Use the collections Module in Python 3](https://davidmuller.github.io/posts/2020/05/08/collections-module-Python3.html) is very useful! Thank you for your work.

"tank-a" to ["Jamie", "Mary"]

should be

"tank-a" to ["Sammy", "Mary"]

**Comment by DavidMuller** [comment]
Hi @vba34520 - thanks for reporting this error to me. It is now fixed in [the post you mentioned](https://davidmuller.github.io/posts/2020/05/08/collections-module-Python3.html)
